version: '3'
services:
  cris-web-server:
    build:
      context: ./docker/backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'  
    depends_on:
      - postgres
  postgres:
    image: postgres:11-bookworm
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=a2b4c6
    ports:
      - '5432:5432'
    volumes:
      - ./docker/backend/postgresql/postgres-data:/var/lib/postgresql/data
