version: '3'
services:  
  postgres:
    image: postgres:11
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=s0m3p4ssw0rd
    ports:
      - '5432:5432'
    volumes:
      - ./docker/backend/postgresql/postgres-data:/var/lib/postgresql/data
      - ./docker/backend/postgresql/init:/docker-entrypoint-initdb.d
  cris-web-server:
    build:
      context: ./docker/backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'  
    # volumes:
    #   - ./docker/backend/solr/solr-data:/home/dspace/solr-data
    depends_on:
      - postgres
    links:
      - postgres
  # cris-ui:
  #   build:
  #     context: ./docker/frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - '4000:4000'
  #   volumes:
  #     - ./docker/frontend/conf_files:/home/conf_files
  #   depends_on:
  #     - cris-web-server
  #   links:
  #     - cris-web-server
