version: '3'
services:  
  postgres:
    image: postgres:11
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=s0m3p4ssw0rd
    ports:
      - '5432:5432'
    volumes:
      - ./docker/backend/postgresql/postgres-data:/var/lib/postgresql/data
      - ./docker/backend/postgresql/init:/docker-entrypoint-initdb.d
  # solr:
  #   image: solr:8.11.2-slim
  #   ports:
  #     - '8983:8983'
  #   volumes:
  #     - ./docker/backend/solr/solr-data:/var/solr/data
  cris-web-server:
    build:
      context: ./docker/backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'  
      - '4000:4000'
      - '8983:8983'
    # volumes:
    #   - ./docker/backend/solr/solr-data:/home/dspace/solr-data
    depends_on:
      - postgres
    links:
      - postgres
